### PR TITLE
remove initial state of brcast

### PR DESCRIPTION
**Pull request by oliviertassinari**
I'm not sure that it makes sense to provide an initial value here

https://github.com/vesparny/brcast/blob/master/index.js#L1

### CODE REVIEW

**Comment by iamstarkov** [comment]
Why it wouldn’t?

**Comment by iamstarkov** [comment]
We rely on this feature, check out broken tests

**Comment by iamstarkov** [comment]
I might miss something, so if it is the case please explain further what did I miss

**Comment by oliviertassinari** [comment]
You are right, this change is not really relevant. As I mentionned before, I have been upgrading the styling solution on Material-UI. I have started with this lib but ended-up reimplementing it to address three issues:
- null theme callback
- default theme value
- wrong propagation of theme when scoped.

I'm not finish yet with the rewrite. I will ping you on the PR so you can have a look at it and eventually port the changes here. Thanks for making this lib!

**Comment by iamstarkov** [comment]
Can I asked you to describe aforementioned issues you faced in more details?

**Comment by oliviertassinari** [comment]
I will, once I have finished the migration. I need to close the circle loop by pushing the changes in production to be sure they are actually something I need and I can consider *issue*.

**Pull request closed without merging**
